server:
  port: 8099
  forward-headers-strategy: framework
  error:
    include-message: always
spring:
  application:
    name: rating
  datasource:
#    url: jdbc:postgresql://localhost:5432/teston199
#    username: admin
#    password: admin
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/ratingDB}
    username: ${DATABASE_USERNAME:admin}
    password: ${DATABASE_PASSWORD:admin}
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
      resolve-lazily: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 50
          batch_versioned_data: true
        order_updates: true
        max_fetch_depth: 2
  jackson:
    serialization:
      fail-on-empty-beans: false
service:
  context: ''
